#!/usr/bin/env python3
"""Generate or diff-check the committed non-semantic authority table."""
from __future__ import annotations

import argparse
import hashlib
import pathlib
import sys
from collections import Counter
from typing import Any

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from authority_surface import (  # noqa: E402
    AUTHORITY_REGISTER_PATH,
    all_operation_authorities,
    read_authority_register,
)


OUTPUT_PATH = HERE / "AUTHORITY_TABLE.md"
# Every status other than `semantic`, in column order. `semantic` names
# authority held by the frozen decision table and is the one status this table
# does not enumerate; the four `*_closure` and `inert_*` statuses are exactly
# the fields whose treatment a reader cannot infer from the frozen table.
NON_SEMANTIC_STATUSES = (
    "semantic_closure",
    "presence_only",
    "presence_only_closure",
    "inert_disclosed",
    "inert_registered_debt",
)
STATUS_HEADINGS = {
    "semantic_closure": "Semantic (closure)",
    "presence_only": "Presence only",
    "presence_only_closure": "Presence only (closure)",
    "inert_disclosed": "Inert disclosed",
    "inert_registered_debt": "Inert registered debt",
}


def _obligation_sort_key(surface: dict[str, Any]) -> tuple[int, str]:
    obligation_id = surface["obligation_id"]
    prefix, separator, suffix = obligation_id.partition("-")
    if prefix == "OBL" and separator and suffix.isdigit():
        return int(suffix), obligation_id
    return sys.maxsize, obligation_id


def _code(value: str) -> str:
    if any(marker in value for marker in ("`", "|", "\r", "\n")):
        raise ValueError(f"identifier cannot be rendered safely in table: {value!r}")
    return f"`{value}`"


def _field_cell(fields: list[dict[str, str]], status: str) -> str:
    names = sorted(field["field"] for field in fields if field["status"] == status)
    return "<br>".join(_code(name) for name in names) if names else "—"


def render_table(register_raw: bytes, register: dict[str, Any]) -> bytes:
    surfaces = sorted(all_operation_authorities(register), key=_obligation_sort_key)
    observed_statuses = {
        field["status"] for surface in surfaces for field in surface["fields"]
    }
    unsupported = observed_statuses - {"semantic", *NON_SEMANTIC_STATUSES}
    if unsupported:
        raise ValueError(
            "authority table has no column for status(es): "
            + ", ".join(sorted(unsupported))
        )

    counts = Counter(
        field["status"] for surface in surfaces for field in surface["fields"]
    )
    source_sha256 = hashlib.sha256(register_raw).hexdigest().upper()
    lines = [
        "<!-- Generated by grounded-0_4/generate_authority_table.py; do not edit. -->",
        "",
        "# Classification authority: required fields outside the frozen table",
        "",
        "This is the one-glance view of every schema-required fact field whose",
        "treatment cannot be read off the frozen decision table. A `(closure)` column",
        "means the field is checked by a tighten-only 0.4 closure predicate rather than",
        "by the frozen table, which is a weaker claim: a closure can turn VALID into a",
        "defect class and can never do the reverse. An em dash means the operation has",
        "no field with that status. Statuses and field membership come only from",
        "`authority_register_0_4.json`.",
        "",
        f"Exact source SHA-256: `{source_sha256}`.",
        "",
        "| Obligation | Operation handle | "
        + " | ".join(STATUS_HEADINGS[status] for status in NON_SEMANTIC_STATUSES)
        + " |",
        "| --- | --- | " + " | ".join("---" for _ in NON_SEMANTIC_STATUSES) + " |",
    ]
    for surface in surfaces:
        fields = surface["fields"]
        lines.append(
            "| "
            + " | ".join(
                (
                    _code(surface["obligation_id"]),
                    _code(surface["operation_handle"]),
                    *(_field_cell(fields, status) for status in NON_SEMANTIC_STATUSES),
                )
            )
            + " |"
        )
    non_semantic_count = sum(counts[status] for status in NON_SEMANTIC_STATUSES)
    lines.extend(
        (
            "",
            (
                f"Operations: {len(surfaces)}. Required fields outside the frozen table: "
                f"{non_semantic_count} ("
                + "; ".join(
                    f"`{status}`: {counts[status]}" for status in NON_SEMANTIC_STATUSES
                )
                + ")."
            ),
            "",
        )
    )
    return "\n".join(lines).encode("utf-8")


def expected_table() -> bytes:
    register_raw, register = read_authority_register(AUTHORITY_REGISTER_PATH)
    return render_table(register_raw, register)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit nonzero unless AUTHORITY_TABLE.md is the exact generated byte stream",
    )
    args = parser.parse_args()
    expected = expected_table()
    if args.check:
        try:
            actual = OUTPUT_PATH.read_bytes()
        except OSError as error:
            print(f"authority table drift: cannot read {OUTPUT_PATH}: {error}")
            return 1
        if actual != expected:
            print(
                "authority table drift: run "
                "python -B grounded-0_4/generate_authority_table.py"
            )
            return 1
        print(
            "authority table: exact generated bytes; "
            f"sha256={hashlib.sha256(actual).hexdigest().upper()}"
        )
        return 0

    OUTPUT_PATH.write_bytes(expected)
    print(
        f"wrote {OUTPUT_PATH}; "
        f"sha256={hashlib.sha256(expected).hexdigest().upper()}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
